### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Juke34** [RAVAO-Ravo/MOD_ML#1]
Hi thank you for this workshop,

Interesting introduction to ML. Would it be possible to add a license in the aim to re-use this introduction for teaching.
CC BY 4.0 wold be nice.

**Comment by RAVAO-Ravo** [comment]
Hi, thank you for attending the workshop, and more generally for attending this year's MODs. I have added a license, I hope it will be useful for you.

**Comment by Juke34** [comment]
Thx
